#nullable enable

namespace ManifestUpdater;

partial class MainForm
{
	private System.ComponentModel.IContainer? components;
	private TableLayoutPanel shellLayout = null!;
	private Panel headerPanel = null!;
	private PictureBox brandIcon = null!;
	private Label titleLabel = null!;
	private Label subtitleLabel = null!;
	private Label securityBadge = null!;
	private StudioButton minimizeButton = null!;
	private StudioButton closeButton = null!;
	private TableLayoutPanel navigationPanel = null!;
	private StudioWorkspaceTabs workspaceTabs = null!;
	private Panel footerPanel = null!;
	private Label statusLabel = null!;
	private StudioBusyIndicator busyProgress = null!;
	private Label modeLabel = null!;

	protected override void Dispose(bool disposing)
	{
		if (disposing) components?.Dispose();
		base.Dispose(disposing);
	}

	private void InitializeComponent()
	{
		components = new System.ComponentModel.Container();
		System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(MainForm));
		shellLayout = new TableLayoutPanel();
		headerPanel = new Panel();
		brandIcon = new PictureBox();
		titleLabel = new Label();
		subtitleLabel = new Label();
		securityBadge = new Label();
		minimizeButton = new StudioButton();
		closeButton = new StudioButton();
		navigationPanel = new TableLayoutPanel();
		workspaceTabs = new StudioWorkspaceTabs();
		footerPanel = new Panel();
		statusLabel = new Label();
		busyProgress = new StudioBusyIndicator();
		modeLabel = new Label();
		shellLayout.SuspendLayout();
		headerPanel.SuspendLayout();
		((System.ComponentModel.ISupportInitialize)brandIcon).BeginInit();
		footerPanel.SuspendLayout();
		SuspendLayout();
		shellLayout.BackColor = StudioPalette.Window;
		shellLayout.ColumnCount = 1;
		shellLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
		shellLayout.Controls.Add(headerPanel, 0, 0);
		shellLayout.Controls.Add(navigationPanel, 0, 1);
		shellLayout.Controls.Add(workspaceTabs, 0, 2);
		shellLayout.Controls.Add(footerPanel, 0, 3);
		shellLayout.Dock = DockStyle.Fill;
		shellLayout.Location = new Point(1, 1);
		shellLayout.Margin = Padding.Empty;
		shellLayout.Name = "shellLayout";
		shellLayout.RowCount = 4;
		shellLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 88F));
		shellLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 58F));
		shellLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
		shellLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 34F));
		shellLayout.Size = new Size(1278, 838);
		shellLayout.TabIndex = 0;
		headerPanel.BackColor = StudioPalette.Header;
		headerPanel.Controls.Add(brandIcon);
		headerPanel.Controls.Add(titleLabel);
		headerPanel.Controls.Add(subtitleLabel);
		headerPanel.Controls.Add(securityBadge);
		headerPanel.Controls.Add(minimizeButton);
		headerPanel.Controls.Add(closeButton);
		headerPanel.Dock = DockStyle.Fill;
		headerPanel.Location = new Point(0, 0);
		headerPanel.Margin = Padding.Empty;
		headerPanel.Name = "headerPanel";
		headerPanel.Size = new Size(1278, 88);
		headerPanel.TabIndex = 0;
		brandIcon.Location = new Point(26, 20);
		brandIcon.Name = "brandIcon";
		brandIcon.Size = new Size(42, 42);
		brandIcon.SizeMode = PictureBoxSizeMode.Zoom;
		brandIcon.TabIndex = 0;
		brandIcon.TabStop = false;
		titleLabel.AutoSize = true;
		titleLabel.Font = new Font("Segoe UI Semibold", 18F, FontStyle.Bold);
		titleLabel.ForeColor = StudioPalette.Text;
		titleLabel.Location = new Point(82, 15);
		titleLabel.Name = "titleLabel";
		titleLabel.Size = new Size(282, 32);
		titleLabel.TabIndex = 1;
		titleLabel.Text = "Winget Manifest Studio";
		subtitleLabel.AutoSize = true;
		subtitleLabel.Font = new Font("Segoe UI", 9.5F);
		subtitleLabel.ForeColor = StudioPalette.Muted;
		subtitleLabel.Location = new Point(84, 52);
		subtitleLabel.Name = "subtitleLabel";
		subtitleLabel.Size = new Size(485, 17);
		subtitleLabel.TabIndex = 2;
		subtitleLabel.Text = "Create, inspect, validate, and submit Windows Package Manager manifests.";
		securityBadge.Anchor = AnchorStyles.Top | AnchorStyles.Right;
		securityBadge.AutoSize = false;
		securityBadge.BackColor = StudioPalette.AccentSoft;
		securityBadge.Font = new Font("Segoe UI Semibold", 8.5F);
		securityBadge.ForeColor = StudioPalette.Accent;
		securityBadge.Location = new Point(916, 25);
		securityBadge.Name = "securityBadge";
		securityBadge.Padding = new Padding(12, 6, 12, 6);
		securityBadge.Size = new Size(230, 34);
		securityBadge.TabIndex = 3;
		securityBadge.Text = "LOCAL-FIRST  •  NO TOKEN STORED";
		securityBadge.TextAlign = ContentAlignment.MiddleCenter;
		minimizeButton.Anchor = AnchorStyles.Top | AnchorStyles.Right;
		minimizeButton.ButtonKind = StudioButtonKind.Title;
		minimizeButton.CornerRadius = 10;
		minimizeButton.Font = new Font("Segoe UI Semibold", 13F);
		minimizeButton.Location = new Point(1168, 22);
		minimizeButton.MinimumSize = new Size(40, 40);
		minimizeButton.Name = "minimizeButton";
		minimizeButton.Padding = Padding.Empty;
		minimizeButton.Size = new Size(40, 40);
		minimizeButton.TabIndex = 4;
		minimizeButton.Text = "—";
		closeButton.Anchor = AnchorStyles.Top | AnchorStyles.Right;
		closeButton.ButtonKind = StudioButtonKind.Danger;
		closeButton.CornerRadius = 10;
		closeButton.Font = new Font("Segoe UI Semibold", 13F);
		closeButton.Location = new Point(1216, 22);
		closeButton.MinimumSize = new Size(40, 40);
		closeButton.Name = "closeButton";
		closeButton.Padding = Padding.Empty;
		closeButton.Size = new Size(40, 40);
		closeButton.TabIndex = 5;
		closeButton.Text = "×";
		navigationPanel.BackColor = StudioPalette.Header;
		navigationPanel.ColumnCount = 1;
		navigationPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
		navigationPanel.Dock = DockStyle.Fill;
		navigationPanel.Location = new Point(0, 88);
		navigationPanel.Margin = Padding.Empty;
		navigationPanel.Name = "navigationPanel";
		navigationPanel.Padding = new Padding(22, 6, 22, 8);
		navigationPanel.RowCount = 1;
		navigationPanel.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
		navigationPanel.Size = new Size(1278, 58);
		navigationPanel.TabIndex = 1;
		workspaceTabs.Appearance = TabAppearance.FlatButtons;
		workspaceTabs.Dock = DockStyle.Fill;
		workspaceTabs.ItemSize = new Size(0, 1);
		workspaceTabs.Location = new Point(0, 146);
		workspaceTabs.Margin = Padding.Empty;
		workspaceTabs.Multiline = true;
		workspaceTabs.Name = "workspaceTabs";
		workspaceTabs.SelectedIndex = 0;
		workspaceTabs.Size = new Size(1278, 658);
		workspaceTabs.SizeMode = TabSizeMode.Fixed;
		workspaceTabs.TabIndex = 2;
		footerPanel.BackColor = StudioPalette.Header;
		footerPanel.Controls.Add(statusLabel);
		footerPanel.Controls.Add(busyProgress);
		footerPanel.Controls.Add(modeLabel);
		footerPanel.Dock = DockStyle.Fill;
		footerPanel.Location = new Point(0, 804);
		footerPanel.Margin = Padding.Empty;
		footerPanel.Name = "footerPanel";
		footerPanel.Size = new Size(1278, 34);
		footerPanel.TabIndex = 3;
		statusLabel.Anchor = AnchorStyles.Left;
		statusLabel.AutoSize = true;
		statusLabel.ForeColor = StudioPalette.Muted;
		statusLabel.Location = new Point(22, 9);
		statusLabel.Name = "statusLabel";
		statusLabel.Size = new Size(39, 15);
		statusLabel.TabIndex = 0;
		statusLabel.Text = "Ready";
		busyProgress.Anchor = AnchorStyles.Left;
		busyProgress.Location = new Point(12, 6);
		busyProgress.Name = "busyProgress";
		busyProgress.Size = new Size(22, 22);
		busyProgress.TabIndex = 1;
		busyProgress.Visible = false;
		modeLabel.Anchor = AnchorStyles.Top | AnchorStyles.Right;
		modeLabel.ForeColor = StudioPalette.Accent;
		modeLabel.Location = new Point(910, 8);
		modeLabel.Name = "modeLabel";
		modeLabel.Size = new Size(346, 17);
		modeLabel.TabIndex = 2;
		modeLabel.Text = "LOCAL AUTHORING READY  •  WINGETCREATE OPTIONAL";
		modeLabel.TextAlign = ContentAlignment.MiddleRight;
		AutoScaleDimensions = new SizeF(7F, 15F);
		AutoScaleMode = AutoScaleMode.Font;
		BackColor = StudioPalette.Border;
		ClientSize = new Size(1280, 840);
		Controls.Add(shellLayout);
		Font = new Font("Segoe UI", 9F);
		ForeColor = StudioPalette.Text;
		FormBorderStyle = FormBorderStyle.None;
		MinimumSize = new Size(1100, 720);
		Name = "MainForm";
		Padding = new Padding(1);
		StartPosition = FormStartPosition.CenterScreen;
		Text = "Winget Manifest Studio";
		shellLayout.ResumeLayout(false);
		headerPanel.ResumeLayout(false);
		headerPanel.PerformLayout();
		((System.ComponentModel.ISupportInitialize)brandIcon).EndInit();
		footerPanel.ResumeLayout(false);
		footerPanel.PerformLayout();
		ResumeLayout(false);
	}
}
