namespace ManifestUpdater;

internal static class StudioLocalization
{
	private static readonly Dictionary<string, string> Spanish = new(StringComparer.Ordinal)
	{
		["Winget Manifest Studio"] = "Winget Manifest Studio",
		["Create, inspect, validate, and submit Windows Package Manager manifests."] = "Crea, inspecciona, valida y envía manifiestos del Administrador de paquetes de Windows.",
		["Start Here"] = "Comenzar",
		["Package Details"] = "Detalles del paquete",
		["Installers & Hashes"] = "Instaladores y hashes",
		["Preview & Submit"] = "Vista previa y envío",
		["Test Center"] = "Centro de pruebas",
		["Help & Guide"] = "Ayuda y guía",
		["Official Tool Commands"] = "Comandos oficiales",
		["1  Start"] = "1  Inicio",
		["2  Package"] = "2  Paquete",
		["3  Installers"] = "3  Instaladores",
		["4  Review"] = "4  Revisar",
		["5  Test Center"] = "5  Centro de pruebas",
		["Help"] = "Ayuda",
		["Official Tools"] = "Herramientas",
		["New Project"] = "Nuevo proyecto",
		["Load Manifests"] = "Cargar manifiestos",
		["Open Profile"] = "Abrir perfil",
		["Save Profile"] = "Guardar perfil",
		["Choose Output"] = "Elegir carpeta",
		["Suggest Package ID"] = "Sugerir ID",
		["Add Release Files"] = "Agregar archivos",
		["Add URL-Only Row"] = "Agregar solo URL",
		["Attach File to Selected"] = "Adjuntar archivo",
		["Inspect & Fill Details"] = "Inspeccionar y completar",
		["Inspect Local Files"] = "Inspeccionar locales",
		["Verify Public URLs"] = "Verificar URL públicas",
		["Remove"] = "Eliminar",
		["Preview Changes"] = "Vista previa",
		["Save Manifests"] = "Guardar manifiestos",
		["Validate Locally"] = "Validar localmente",
		["Open Test Center"] = "Abrir centro de pruebas",
		["Submit to Winget"] = "Enviar a Winget",
		["Open Output Folder"] = "Abrir carpeta",
		["Technical Details"] = "Detalles técnicos",
		["Simple Review"] = "Revisión sencilla",
		["Run Safe Preflight"] = "Ejecutar revisión segura",
		["Inspect Signatures"] = "Inspeccionar firmas",
		["Find Existing Package"] = "Buscar paquete existente",
		["Export Test Report"] = "Exportar informe",
		["Enable Local Testing"] = "Habilitar prueba local",
		["Test Install Here"] = "Probar instalación aquí",
		["Verify Installed Result"] = "Verificar instalación",
		["Test in Windows Sandbox"] = "Probar en Windows Sandbox",
		["Use Current Project"] = "Usar proyecto actual",
		["Install WingetCreate"] = "Instalar WingetCreate",
		["Run"] = "Ejecutar",
		["PACKAGE WORKSPACE"] = "ÁREA DEL PAQUETE",
		["PACKAGE IDENTITY"] = "IDENTIDAD DEL PAQUETE",
		["PUBLIC PACKAGE INFORMATION"] = "INFORMACIÓN PÚBLICA",
		["PROJECT LINKS & RELEASE"] = "ENLACES Y VERSIÓN",
		["INSTALLER BEHAVIOR"] = "COMPORTAMIENTO DEL INSTALADOR",
		["INSTALLER SWITCHES"] = "PARÁMETROS DEL INSTALADOR",
		["ALL OTHER SCHEMA FIELDS"] = "OTROS CAMPOS DEL ESQUEMA",
		["INSTALLER DETAILS ARE AUTOMATIC"] = "LOS DETALLES SON AUTOMÁTICOS",
		["REVIEW BEFORE SAVING"] = "REVISAR ANTES DE GUARDAR",
		["TEST BEFORE SUBMITTING"] = "PROBAR ANTES DE ENVIAR",
		["INSTALLATION TESTS REQUIRE YOUR CONFIRMATION"] = "LAS PRUEBAS DE INSTALACIÓN REQUIEREN CONFIRMACIÓN",
		["HOW TO USE THIS SOFTWARE"] = "CÓMO USAR ESTE PROGRAMA",
		["COMMON PROBLEMS"] = "PROBLEMAS COMUNES",
		["Language"] = "Idioma",
		["English"] = "English",
		["Español"] = "Español",
		["Package identifier"] = "Identificador del paquete",
		["Package version"] = "Versión del paquete",
		["Default locale"] = "Idioma predeterminado",
		["Winget schema"] = "Esquema de Winget",
		["Manifest output folder"] = "Carpeta de manifiestos",
		["Package name"] = "Nombre del paquete",
		["Publisher"] = "Editor",
		["Author"] = "Autor",
		["License"] = "Licencia",
		["Short description"] = "Descripción breve",
		["Full description"] = "Descripción completa",
		["Tags"] = "Etiquetas",
		["Commands"] = "Comandos",
		["Release notes"] = "Notas de la versión",
		["Installation notes"] = "Notas de instalación",
		["Ready"] = "Listo"
	};

	public static bool IsSupported(string language) => language is "en-US" or "es-ES";

	public static string Translate(string english, string language)
	{
		if (!language.Equals("es-ES", StringComparison.OrdinalIgnoreCase)) return english;
		return Spanish.GetValueOrDefault(english, english);
	}
}
